#pragma once

#include "mlfe/operators/basic_arithmetic.h"
#include "mlfe/operators/batch_norm1d.h"
#include "mlfe/operators/batch_norm2d.h"
#include "mlfe/operators/broadcast.h"
#include "mlfe/operators/conv2d.h"
#include "mlfe/operators/dropout.h"
#include "mlfe/operators/global_avg_pool2d.h"
#include "mlfe/operators/matmul.h"
#include "mlfe/operators/maxpool2d.h"
#include "mlfe/operators/relu.h"
#include "mlfe/operators/reduce_mean.h"
#include "mlfe/operators/sigmoid.h"
#include "mlfe/operators/sigmoid_cross_entropy.h"
#include "mlfe/operators/softmax_cross_entropy.h"
#include "mlfe/operators/squared_difference.h"
