function(find_mkldnn )
    set(MKLDNN_FOUND FALSE)
    find_path(MKLDNN_INCLUDE_DIR mkldnn.h)
    find_library(MKLDNN_LIB mkldnn)

    if(MKLDNN_INCLUDE_DIR AND MKLDNN_LIB)
        set(MKLDNN_FOUND TRUE)
    endif()

    if(MKLDNN_FOUND)
        set(MKLDNN_INCLUDE_DIRS ${MKLDNN_INCLUDE_DIR} PARENT_SCOPE)
        set(MKLDNN_LIBS ${MKLDNN_LIB} PARENT_SCOPE)
        set(MKLDNN_FOUND TRUE PARENT_SCOPE)
    endif()
endfunction()
